# Generated by Django 5.0.4 on 2024-05-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Polish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Polish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Polish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Polish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Polish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Polish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Polish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Polish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Polish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Polish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Polish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Polish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Polish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Polish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('priority_name', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Priority_Name', max_length=255, null=True)),
                ('color_number', models.IntegerField(blank=True, db_column='Color_Number', null=True)),
            ],
            options={
                'db_table': 'Priorities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projekty',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Project_Name', max_length=255, null=True)),
                ('team_id', models.IntegerField(blank=True, db_column='Team_ID', null=True)),
                ('date_start', models.DateField(blank=True, db_column='Date_Start', null=True)),
                ('date_end', models.DateField(blank=True, db_column='Date_End', null=True)),
                ('description', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Projekty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Status_Name', max_length=255, null=True)),
                ('color_nr', models.IntegerField(blank=True, db_column='Color_Nr', null=True)),
            ],
            options={
                'db_table': 'Statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='Polish_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Task_Name', max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, db_column='Date_Start', null=True)),
                ('date_end', models.DateField(blank=True, db_column='Date_End', null=True)),
                ('description', models.CharField(blank=True, db_collation='Polish_CI_AS', db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.projekty')),
                ('team_id', models.IntegerField(blank=True, db_column='Team_ID', null=True)),
            ],
            options={
                'db_table': 'Teams',
                'managed': False,
            },
        ),
    ]
